In [12]:
import numpy as np
x = np.arange(10).reshape(5,2)
print (x)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [9]:
print (x)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [14]:
print(np.square(x))

print(np.sqrt(x))

print(np.cos(x))

[[ 0  1]
 [ 4  9]
 [16 25]
 [36 49]
 [64 81]]
[[ 0.          1.        ]
 [ 1.41421356  1.73205081]
 [ 2.          2.23606798]
 [ 2.44948974  2.64575131]
 [ 2.82842712  3.        ]]
[[ 1.          0.54030231]
 [-0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219]
 [ 0.96017029  0.75390225]
 [-0.14550003 -0.91113026]]


In [15]:
print(np.max(x))

print(np.min(x))

print(np.mean(x))

print(np.std(x))


9
0
4.5
2.87228132327
